### ISSUE TITLE
rss?

### ISSUE THREAD

**Issue by dongdigua** [include-yy/egh0bww1#1]
wow, first issue  
can you add rss to your blog so I can subscribe?  
your blog is of really high quality

**Comment by include-yy** [comment]
thanks for your compliment, it's my pleasure. I didn't think anyone would read my blogs before your issue.
I'll do this two or three days later, when I finish I will tell you through this issue

**Comment by include-yy** [comment]
Done, it was easier than I thought.
Now I "generate" the rss by hand, maybe later I'll consider writing an elisp plugin to automate it.
I'll update rss.xml after I write a new article that I think is good.
